export const words = {
  ru: {
    loaderText: 'Загружаем меню. <br> Пожалуйста подождите.',
    appError: 'Простите приложение временно недоступно. Пожалуйста обратитесь к официантку.',
    discountButtonText: 'Предложение дня',
    visitorNnativeLanguage: "Родной язык посетителя - ",
    portion: "порция",
    cost: "стоимость",
    pieces: "штуки",

    totalCost: "Стоимость блюд в корзине: <br>",
    yourOrderTitle: "Ваш заказ",
    sendOrder: "Отправить заказ",
    updateOrder: "Добавить к заказу",

    yourCart: "Корзина:",
    announcement: "",
    announcementText: "Выберите желаемые блюда, затем пригласите официанта и покажите ему корзину.",
    googleFedback: "Оставьте отзыв",
    deletePortionMessage: "Удалить порцию?",

    textSendOrder: "Заказ успешно отправлен!",
    textErrorSendOrder: "Ошибка при отправке заказа. Пожалуйста, попробуйте ещё раз или пригласите официанта.",
    textAskTableNumber: "Пожалуйста, введите номер стола. Его можно увидеть на QR-коде, который находится на вашем столе.",
    totalCostOrder: "Стоимость заказа: ",
    yourOrderButton: "Ваш заказ<br>№",
    payOrderButton: "Оплатить",

    tableNumber: "🍽️ Стол № ",
    orderNumber: "#️⃣ Номер заказа",
    newOrderMessage: "‼️🔴 Новый заказ!\n",
    updateOrderMessage: "‼️🟢 Обновление заказа\n",
    oldDishes: "🟨 Прошлые блюда:",
    newDishes: "🟩 Новые блюда:",
    listDishes: "📃 Список блюд:",

    IQRMenuLink: "Заказать меню",
    selectPaymentMethod: "Выберете способ оплаты",
    cash: "Наличные",
    bankCard: "Карта",
    cancelButton: "Отмена",
    waiterWillCome: "Спасибо! Скоро к вам придет официант.",
    errorInviteWaiter: "Что-то пошло не так, пожалуйста пригласите официанта",
    enterCorrectly: "Пожалуйста введите корректно номер стола",
    errorPayCode: "Неверный код! Пожалуйста уточните у официанта.",
    finishText: "Спасибо! Ждем Вас вновь!",
    inputPayCodeText: "Сейчас к вам придет официант. После оплаты пожалуйста введите код оплаты. Официант вам его сообщит.",
    textMessage: "💵 Оплата заказа!\n\nРодной язык посетителя - ${userLang}\n🍽️ Стол № ${tableNumber}\n💶💳 Способ оплаты - ${paymentMethod}\n#️⃣ Номер закза -\n${orderId}\n\n📃 Вот чек:\n ${orderListText}\n💰 Итого: ${totalCostMessage} ${currencySymbol}\n\n Код - Успешная оплата: ${sectetPayCode}",


  },
  en: {
    loaderText: 'Loading menu.<br>Please wait.',
    appError: 'Sorry, the app is temporarily unavailable. Please contact the waitress.',
    discountButtonText: 'Offer of the day',
    visitorNnativeLanguage: "Visitor's native language - ",
    portion: "portion",
    cost: "cost",
    pieces: "pieces",

    totalCost: "Total cost of dishes in the cart: <br>",
    yourOrderTitle: "Your order",
    sendOrder: "Send order",
    updateOrder: "Add to order",

    yourCart: "Cart:",
    announcement: "",
    announcementText: "Select the desired dishes, then call the waiter and show them the cart.",
    googleFedback: "Leave feedback",
    deletePortionMessage: "Delete portion?",

    textSendOrder: "Order sent successfully!",
    textErrorSendOrder: "Error sending order. Please try again or call the waiter.",
    textAskTableNumber: "Please enter your table number. You can find it on the QR code located on your table.",
    totalCostOrder: "Order cost: ",
    yourOrderButton: "Your order<br>№",

    tableNumber: "🍽️Table № ",
    orderNumber: "#️⃣ Order number",
    newOrderMessage: "‼️🔴 New order!\n",
    updateOrderMessage: "‼️🟢 Order update\n",
    oldDishes: "🟨 Previous dishes:",
    newDishes: "🟩 New dishes:",
    listDishes: "📃 List of dishes:",
    payOrderButton: "Pay",

    IQRMenuLink: "Order menu",
    selectPaymentMethod: "Choose a payment method",
    cash: "Cash",
    bankCard: "Card",
    cancelButton: "Cancel",
    waiterWillCome: "Thank you! A waiter will come to you soon.",
    errorInviteWaiter: "Something went wrong, please call a waiter.",
    enterCorrectly: "Please enter the table number correctly.",
    errorPayCode: "Invalid code! Please check with the waiter.",
    finishText: "Thank you! We look forward to seeing you again!",
    inputPayCodeText: "The waiter will be with you shortly. After making the payment, please enter the payment code that they will provide.",
    textMessage: "💵 Order payment!\n\nVisitor's native language - ${userLang}\n🍽️ Table № ${tableNumber}\n💶💳 Payment method - ${paymentMethod}\n#️⃣ Order number -\n${orderId}\n\n📃 Here is the receipt:\n ${orderListText}\n💰 Total: ${totalCostMessage} ${currencySymbol}\n\n Payment Success Code: ${sectetPayCode}"
  },
  es: {
    loaderText: 'Cargando menú.<br>Por favor espere.',
    appError: 'Lo sentimos, la aplicación no está disponible temporalmente. Por favor pregunte a la camarera.',
    discountButtonText: 'Oferta del día',
    visitorNnativeLanguage: "Idioma nativo del visitante - ",
    portion: "porción",
    cost: "costo",
    pieces: "piezas",

    totalCost: "Costo total de los platos en el carrito: <br>",
    yourOrderTitle: "Tu pedido",
    sendOrder: "Enviar pedido",
    updateOrder: "Agregar al pedido",

    yourCart: "Carrito:",
    announcement: "",
    announcementText: "Selecciona los platos deseados, luego llama al mesero y muéstrale el carrito.",
    googleFedback: "Deja tu opinión",
    deletePortionMessage: "¿Eliminar porción?",

    textSendOrder: "¡Pedido enviado con éxito!",
    textErrorSendOrder: "Error al enviar el pedido. Por favor, inténtalo de nuevo o llama al mesero.",
    textAskTableNumber: "Por favor, ingresa el número de tu mesa. Puedes encontrarlo en el código QR ubicado en tu mesa.",
    totalCostOrder: "Costo del pedido: ",
    yourOrderButton: "Tu pedido<br>№",

    tableNumber: "🍽️ Mesa № ",
    orderNumber: "#️⃣ Número de pedido",
    newOrderMessage: "‼️🔴 ¡Nuevo pedido!\n",
    updateOrderMessage: "‼️🟢 Actualización del pedido\n",
    oldDishes: "🟨 Platos anteriores:",
    newDishes: "🟩 Platos nuevos:",
    listDishes: "📃 Lista de platos:",
    payOrderButton: "Pagar",

    IQRMenuLink: "Pedir menú",
    selectPaymentMethod: "Elige un método de pago",
    cash: "Efectivo",
    bankCard: "Tarjeta",
    cancelButton: "Cancelar",
    waiterWillCome: "¡Gracias! Un mesero vendrá pronto.",
    errorInviteWaiter: "Algo salió mal, por favor llama a un mesero.",
    enterCorrectly: "Por favor, ingresa correctamente el número de mesa.",
    errorPayCode: "¡Código incorrecto! Por favor, consúltelo con el mozo.",
    finishText: "¡Gracias! ¡Los esperamos de nuevo!",
    inputPayCodeText: "En breve llegará el mozo. Después de realizar el pago, por favor ingrese el código de pago que él le proporcionará.",
    textMessage: "💵 ¡Pago del pedido!\n\nIdioma nativo del visitante - ${userLang}\n🍽️ Mesa Nº ${tableNumber}\n💶💳 Método de pago - ${paymentMethod}\n#️⃣ Número de pedido -\n${orderId}\n\n📃 Aquí está el recibo:\n ${orderListText}\n💰 Total: ${totalCostMessage} ${currencySymbol}\n\n Código de Pago Exitoso: ${sectetPayCode}"
  },
  pt: {
    loaderText: 'Carregando o menu.<br>Por favor aguarde.',
    appError: 'Desculpe, o aplicativo está temporariamente indisponível. Por favor, pergunte à garçonete.',
    discountButtonText: 'Oferta do dia',
    visitorNnativeLanguage: "Idioma nativo do visitante - ",
    portion: "porção",
    cost: "custo",
    pieces: "peças",

    totalCost: "Custo total dos pratos no carrinho: <br>",
    yourOrderTitle: "Seu pedido",
    sendOrder: "Enviar pedido",
    updateOrder: "Adicionar ao pedido",

    yourCart: "Carrinho:",
    announcement: "",
    announcementText: "Selecione os pratos desejados, depois chame o garçom e mostre o carrinho.",
    googleFedback: "Deixe sua opinião",
    deletePortionMessage: "Remover porção?",

    textSendOrder: "Pedido enviado com sucesso!",
    textErrorSendOrder: "Erro ao enviar o pedido. Por favor, tente novamente ou chame o garçom.",
    textAskTableNumber: "Por favor, insira o número da sua mesa. Você pode encontrá-lo no código QR localizado na sua mesa.",
    totalCostOrder: "Custo do pedido: ",
    yourOrderButton: "Seu pedido<br>№",
    payOrderButton: "Pagar",

    tableNumber: "🍽️ Mesa № ",
    orderNumber: "#️⃣ Número do pedido",
    newOrderMessage: "‼️🔴 Novo pedido!\n",
    updateOrderMessage: "‼️🟢 Atualização do pedido\n",
    oldDishes: "🟨 Pratos anteriores:",
    newDishes: "🟩 Pratos novos:",
    listDishes: "📃 Lista de pratos:",

    IQRMenuLink: "Pedir cardápio",
    selectPaymentMethod: "Escolha um método de pagamento",
    cash: "Dinheiro",
    bankCard: "Cartão",
    cancelButton: "Cancelar",
    waiterWillCome: "Obrigado! Um garçom virá até você em breve.",
    errorInviteWaiter: "Algo deu errado, por favor, chame um garçom.",
    enterCorrectly: "Por favor, insira o número da mesa corretamente.",
    errorPayCode: "Código incorreto! Por favor, confirme com o garçom.",
    finishText: "Obrigado! Esperamos vê-lo novamente!",
    inputPayCodeText: "O garçom chegará em breve. Após o pagamento, por favor, insira o código de pagamento que ele lhe informará.",
    textMessage: "💵 Pagamento do pedido!\n\nIdioma nativo do visitante - ${userLang}\n🍽️ Mesa nº ${tableNumber}\n💶💳 Método de pagamento - ${paymentMethod}\n#️⃣ Número do pedido -\n${orderId}\n\n📃 Aqui está o recibo:\n ${orderListText}\n💰 Total: ${totalCostMessage} ${currencySymbol}\n\n Código de Pagamento Bem-Sucedido: ${sectetPayCode}"
  },
}